# config.yml

backend:
  name: github
  branch: gh-pages # Branch to update (optional; defaults to master)
  repo: etalab/entreprise.api.gouv.fr
  site_domain: nostalgic-panini-814b9c.netlify.com
local_backend: true
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'pages/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { name: Title }
  - name: 'catalogue'
    label: 'Catalogue de données'
    label_singular: 'Endpoint'
    folder: '_catalogue'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - label: 'Type de données'
        name: 'type'
        widget: 'select'
        options: ['Informations générales', 'Informations financières', 'Attestations sociales et fiscales', 'Certifications professionnelles', 'Propriété intellectuelle' ]
      - { label: 'Nom', name: 'title', widget: 'string' }
      - { label: 'Endpoint', name: 'label', widget: 'string' }
      - label: 'Type de personne morale'
        name: 'scope'
        widget: 'select'
        multiple: true
        options: ['entreprises', 'associations']
      - { label: 'Description courte', name: 'description', widget: 'markdown' }
      - label: 'Cas d’usage'
        name: 'usecases'
        widget: 'select'
        multiple: true
        options: ['Aides publiques', 'Marchés publics', 'Application de la loi énergie - Art.64', 'Répertoire de tiers', "Aide d'urgence Covid-19"]
      - label: 'Accès'
        name: 'access'
        widget: 'select'
        multiple: true
        options: ['restreint', 'libre', "restreint, disponible sous d'autres conditions"]
      - label: 'Fournisseurs'
        name: 'providers'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Infogreffe', value: 'infogreffe' }
          - { label: 'INSEE', value: 'insee' }
          - { label: 'DGFIP', value: 'dgfip' }
          - { label: 'ACOSS', value: 'acoss' }
          - { label: 'INPI', value: 'inpi' }
          - { label: 'Qualibat', value: 'qualibat' }
          - { label: 'Répertoire National des Assocations', value: 'rna' }
          - { label: 'CNETP', value: 'cnetp' }
          - { label: 'ProBTP', value: 'probtp' }
          - { label: 'MSA', value: 'msa' }
          - { label: 'OPQIBI', value: 'opqibi' }
          - { label: 'FNTP', value: 'fntp' }
          - { label: 'agefiph', value: 'agefiph' }
      - { label: 'Nouvelle option disponible', name: 'new', required: false , widget: 'markdown' }
      - label: 'Périmètre'
        name: 'perimeter'
        widget: 'object'
        required: false
        fields:
        - label: 'Périmètre 1'
          name: 'perimeter1'
          required: false
          widget: 'object'
          fields:
            - label: 'Label'
              name: 'label'
              required: false
              widget: 'string'
            - label: 'Description'
              name: 'description'
              required: false
              widget: 'markdown'
        - label: 'Périmètre 2'
          name: 'perimeter2'
          required: false
          widget: 'object'
          fields:
            - label: 'Label'
              name: 'label'
              required: false
              widget: 'string'
            - label: 'Description'
              name: 'description'
              required: false
              widget: 'markdown'
        - label: 'Périmètre 3'
          name: 'perimeter3'
          required: false
          widget: 'object'
          fields:
            - label: 'Label'
              name: 'label'
              required: false
              widget: 'string'
            - label: 'Description'
              name: 'description'
              required: false
              widget: 'markdown'
      - label: 'Requête'
        name: 'request'
        widget: 'object'
        fields:
          - label: 'Paramètres'
            name: 'parameters'
            required: false
            widget: 'object'
            fields:
            - label: 'Paramètre d’appel'
              name: 'id'
              description: 'A remplir avec le paramètre permettant d’identifier une entité'
              required: false
              widget: 'object'
              fields:
                - label: 'Paramètre'
                  name: 'parameter'
                  required: false
                  widget: 'string'
                - label: 'Description'
                  name: 'description'
                  required: false
                  widget: 'string'
            - label: 'Paramètre'
              name: 'param1'
              required: false
              widget: 'object'
              fields:
                - label: 'Paramètre'
                  name: 'label'
                  required: false
                  widget: 'string'
                - label: 'Description'
                  name: 'description'
                  required: false
                  widget: 'string'
            - label: 'Paramètre'
              name: 'param2'
              required: false
              widget: 'object'
              fields:
                - label: 'Paramètre'
                  name: 'label'
                  required: false
                  widget: 'string'
                - label: 'Description'
                  name: 'description'
                  required: false
                  widget: 'string'
            - label: 'Paramètre'
              name: 'param3'
              required: false
              widget: 'object'
              fields:
                - label: 'Paramètre'
                  name: 'label'
                  required: false
                  widget: 'string'
                - label: 'Description'
                  name: 'description'
                  required: false
                  widget: 'string'
            - label: 'Paramètre'
              name: 'param4'
              required: false
              widget: 'object'
              fields:
                - label: 'Paramètre'
                  name: 'label'
                  required: false
                  widget: 'string'
                - label: 'Description'
                  name: 'description'
                  required: false
                  widget: 'string'
            - label: 'Paramètre'
              name: 'param5'
              required: false
              widget: 'object'
              fields:
                - label: 'Paramètre'
                  name: 'label'
                  required: false
                  widget: 'string'
                - label: 'Description'
                  name: 'description'
                  required: false
                  widget: 'string'
          - label: 'Options'
            name: 'options'
            required: false
            widget: 'object'
            fields:
              - label: 'Option 1'
                name: 'option1'
                required: false
                widget: 'object'
                fields:
                  - label: 'Paramètre'
                    name: 'param'
                    required: false
                    widget: 'string'
                  - label: 'Description'
                    name: 'description'
                    required: false
                    width: 'string'
                  - label: 'Commentaire'
                    name: 'comment'
                    required: false
                    widget: 'string'
              - label: 'Option 2'
                name: 'option2'
                required: false
                widget: 'object'
                fields:
                  - label: 'Paramètre'
                    name: 'param'
                    required: false
                    widget: 'string'
                  - label: 'Description'
                    name: 'description'
                    required: false
                    width: 'string'
                  - label: 'Commentaire'
                    name: 'comment'
                    required: false
                    widget: 'string'
              - label: 'Option 3'
                name: 'option3'
                required: false
                widget: 'object'
                fields:
                  - label: 'Paramètre'
                    name: 'param'
                    required: false
                    widget: 'string'
                  - label: 'Description'
                    name: 'description'
                    required: false
                    width: 'string'
                  - label: 'Commentaire'
                    name: 'comment'
                    required: false
                    widget: 'string'
      - label: 'Réponse'
        name: 'response'
        required: false
        widget: 'object'
        fields:
          - label: 'Format'
            name: 'format'
            required: false
            default: 'Données structurées JSON'
            widget: 'string'
          - label: 'Timeout'
            name: 'timeout'
            required: false
            widget: 'string'
          - label: 'Description'
            name: 'description'
            required: false
            widget: 'markdown'
      - label: 'Historique'
        name: 'history'
        required: false
        widget: 'markdown'
